import pytest
from datetime import timedelta
from unittest.mock import AsyncMock
from httpx import AsyncClient
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_token,
)
from app.models.enums import UserRole
from app.main import app
from app.db.session import get_db

@pytest.mark.asyncio
async def test_bcrypt_nextjs_known_hash_compatibility():
    """Verify that bcrypt password hashes generated by Next.js bcryptjs match Python bcrypt."""
    plain_pass = "123456"
    hashed_pass = hash_password(plain_pass)
    assert verify_password(plain_pass, hashed_pass) is True
    assert verify_password("wrongpassword", hashed_pass) is False

@pytest.mark.asyncio
async def test_access_token_claims():
    user_id = "user-uuid-123"
    token = create_access_token(user_id=user_id, role="OWNER", token_version=1)
    payload = decode_token(token)
    assert payload["sub"] == user_id
    assert payload["role"] == "OWNER"
    assert payload["type"] == "access"
    assert payload["tokenVersion"] == 1

@pytest.mark.asyncio
async def test_refresh_token_claims():
    user_id = "user-uuid-123"
    token = create_refresh_token(user_id=user_id, token_version=2)
    payload = decode_token(token)
    assert payload["sub"] == user_id
    assert payload["type"] == "refresh"
    assert payload["tokenVersion"] == 2

@pytest.mark.asyncio
async def test_expired_token_rejection():
    user_id = "user-uuid-123"
    token = create_access_token(user_id=user_id, role="TENANT", expires_delta=timedelta(seconds=-10))
    with pytest.raises(ValueError) as exc_info:
        decode_token(token)
    assert "expired" in str(exc_info.value).lower()

@pytest.mark.asyncio
async def test_health_liveness(async_client: AsyncClient):
    response = await async_client.get("/api/v1/health")
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["data"]["status"] == "OK"
    assert "requestId" in data

@pytest.mark.asyncio
async def test_readiness_probe_success(async_client: AsyncClient):
    mock_db = AsyncMock()
    mock_db.execute = AsyncMock()
    app.dependency_overrides[get_db] = lambda: mock_db

    response = await async_client.get("/api/v1/health/ready")
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["data"]["status"] == "READY"
    assert data["data"]["database"] == "HEALTHY"

    app.dependency_overrides.clear()

@pytest.mark.asyncio
async def test_readiness_probe_db_failure(async_client: AsyncClient):
    mock_db = AsyncMock()
    mock_db.execute.side_effect = Exception("Connection refused")
    app.dependency_overrides[get_db] = lambda: mock_db

    response = await async_client.get("/api/v1/health/ready")
    assert response.status_code == 503
    data = response.json()
    assert data["success"] is False
    assert data["code"] == "HTTP_503"
    assert "Cơ sở dữ liệu không khả dụng" in data["message"]

    app.dependency_overrides.clear()

@pytest.mark.asyncio
async def test_unauthorized_missing_token(async_client: AsyncClient):
    response = await async_client.get("/api/v1/auth/me")
    assert response.status_code == 401
    data = response.json()
    assert data["success"] is False
    assert data["code"] == "HTTP_401"
    assert "requestId" in data

@pytest.mark.asyncio
async def test_invalid_token_rejected(async_client: AsyncClient):
    headers = {"Authorization": "Bearer malformed.invalid.token"}
    response = await async_client.get("/api/v1/auth/me", headers=headers)
    assert response.status_code == 401
    data = response.json()
    assert data["success"] is False
    assert "Phiên làm việc không hợp lệ" in data["message"]
    assert "requestId" in data

@pytest.mark.asyncio
async def test_access_token_at_refresh_endpoint_rejected(async_client: AsyncClient):
    access_token = create_access_token(user_id="user-123", role="OWNER")
    cookies = {"refreshToken": access_token}
    response = await async_client.post("/api/v1/auth/refresh", cookies=cookies)
    assert response.status_code == 401
    data = response.json()
    assert data["success"] is False
    assert "không phải là refresh token" in data["message"]

@pytest.mark.asyncio
async def test_refresh_token_at_protected_endpoint_rejected(async_client: AsyncClient):
    """Refresh token must not be accepted at protected API endpoints expecting access tokens."""
    refresh_token = create_refresh_token(user_id="user-123")
    headers = {"Authorization": f"Bearer {refresh_token}"}
    response = await async_client.get("/api/v1/auth/me", headers=headers)
    assert response.status_code == 401

@pytest.mark.asyncio
async def test_all_3_roles_enum():
    assert UserRole.SUPER_ADMIN.value == "SUPER_ADMIN"
    assert UserRole.OWNER.value == "OWNER"
    assert UserRole.TENANT.value == "TENANT"
